"""First-party, per-user NSIS development installer using only core/zlib opcodes.

No StdUtils, Nsis7z, UAC or other resource plug-in is loaded or embedded. The
uninstaller enumerates only installed program files and removes empty directories.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
NSIS_COPYING_SHA256 = "3c8de989f6504d52f5f8dfafedb6668cd47201f5d01f1319570727c091425dd6"
NSIS_WINDOWS_COMPILER_SHA256 = "e277b7378931b74392015f5ad6b1d744dcd8a347baa4480350a75ebeab8d8e3d"
NSIS_LINUX_COMPILER_SHA256 = "4c9ef29d87623f72163eadd8de1b63811f7aa85fd18352559315dac58da83844"
PRODUCT = "AIVORA Dev Core"
REGISTRY_KEY = r"Software\Microsoft\Windows\CurrentVersion\Uninstall\AIVORA-Dev-Core"


def digest(path: Path) -> str:
    with path.open("rb") as stream:
        return hashlib.file_digest(stream, "sha256").hexdigest()


def literal(value: str) -> str:
    if any(ord(character) < 32 for character in value):
        raise ValueError("Control characters cannot appear in an installer path")
    return '"' + value.replace("$", "$$").replace('"', '$\\"') + '"'


def program_files(app: Path) -> dict[str, str]:
    files = {}
    for path in sorted(app.rglob("*")):
        if path.is_symlink() or path.is_junction():
            raise ValueError("Installed program tree cannot contain a link or junction")
        if path.is_file():
            relative = path.relative_to(app).as_posix()
            if any(part in {"", ".", ".."} for part in relative.split("/")) or ":" in relative:
                raise ValueError("Unsafe installed program path")
            if relative.lower() == "uninstall.exe":
                raise ValueError("Input collides with the generated uninstaller")
            files[relative] = digest(path)
        elif not path.is_dir():
            raise ValueError("Installer only accepts plain files/directories")
    if PRODUCT + ".exe" not in files:
        raise ValueError("The packaged development application executable is absent")
    return files


def generate_script(app: Path, installer: Path, hook: Path) -> tuple[str, dict[str, str]]:
    files = program_files(app)
    lines = [
        "; Generated by AIVORA's first-party development installer emitter.",
        "Unicode true",
        "RequestExecutionLevel user",
        "SetCompressor /FINAL zlib",
        "AutoCloseWindow true",
        "ShowInstDetails show",
        "ShowUninstDetails show",
        'Name "AIVORA Dev Core"',
        "OutFile " + literal(str(installer)),
        'InstallDir "$LOCALAPPDATA\\Programs\\AIVORA Dev Core"',
        'VIProductVersion "0.1.0.0"',
        'VIAddVersionKey "ProductName" "AIVORA Dev Core"',
        'VIAddVersionKey "FileDescription" "Unsigned development core installer"',
        'VIAddVersionKey "FileVersion" "0.1.0-dev.core"',
        'VIAddVersionKey "LegalCopyright" "Copyright 2026 Aijian Studio contributors"',
        "!define INSTALL_REGISTRY_KEY " + literal(REGISTRY_KEY),
        "!include " + literal(str(hook)),
        "Page instfiles",
        "UninstPage instfiles",
        "Function .onInit",
        "  SetShellVarContext current",
        "  !insertmacro customInit",
        # Reject unrelated occupied destinations, in addition to known app/data.
        '  IfFileExists "$INSTDIR\\*.*" aivoraOccupiedTarget aivoraEmptyTarget',
        "aivoraOccupiedTarget:",
        '  MessageBox MB_ICONSTOP|MB_OK "Choose a new empty installation directory. '
        'Existing files will not be replaced." /SD IDOK',
        "  SetErrorLevel 2",
        "  Abort",
        "aivoraEmptyTarget:",
        '  IfFileExists "$SMPROGRAMS\\AIVORA Dev Core\\*.*" aivoraOccupiedTarget 0',
        "FunctionEnd",
        "Function un.onInit",
        "  SetShellVarContext current",
        "FunctionEnd",
        'Section "Install"',
    ]
    previous = None
    directories = set()
    for relative in files:
        path = Path(relative)
        directory = path.parent.as_posix()
        if directory != previous:
            suffix = "" if directory == "." else "\\" + directory.replace("/", "\\")
            # INSTDIR is our intentional NSIS variable; all input-derived text is escaped.
            escaped = suffix.replace("$", "$$").replace('"', '$\\"')
            lines += [
                "  ClearErrors",
                '  SetOutPath "$INSTDIR' + escaped + '"',
                "  IfErrors aivoraInstallFailed",
            ]
            previous = directory
        lines += [
            "  ClearErrors",
            "  File " + literal(str(app / relative)),
            "  IfErrors aivoraInstallFailed",
        ]
        for parent in path.parents:
            if parent.as_posix() != ".":
                directories.add(parent.as_posix())
    lines += [
        '  WriteUninstaller "$INSTDIR\\Uninstall.exe"',
        "  IfErrors aivoraInstallFailed",
        '  WriteRegStr HKCU "${INSTALL_REGISTRY_KEY}" "DisplayName" "AIVORA Dev Core"',
        '  WriteRegStr HKCU "${INSTALL_REGISTRY_KEY}" "DisplayVersion" "0.1.0-dev.core"',
        '  WriteRegStr HKCU "${INSTALL_REGISTRY_KEY}" "InstallLocation" "$INSTDIR"',
        '  WriteRegStr HKCU "${INSTALL_REGISTRY_KEY}" "UninstallString" '
        "'$\\\"$INSTDIR\\Uninstall.exe$\\\"'",
        '  WriteRegDWORD HKCU "${INSTALL_REGISTRY_KEY}" "NoModify" 1',
        '  WriteRegDWORD HKCU "${INSTALL_REGISTRY_KEY}" "NoRepair" 1',
        '  CreateDirectory "$SMPROGRAMS\\AIVORA Dev Core"',
        '  CreateShortCut "$SMPROGRAMS\\AIVORA Dev Core\\AIVORA Dev Core.lnk" '
        '"$INSTDIR\\AIVORA Dev Core.exe"',
        '  CreateShortCut "$SMPROGRAMS\\AIVORA Dev Core\\Uninstall.lnk" "$INSTDIR\\Uninstall.exe"',
        "  Goto aivoraInstallDone",
        "aivoraInstallFailed:",
        '  MessageBox MB_ICONSTOP|MB_OK "Installation could not finish. '
        'No user workspace was changed; the partial program directory was retained." /SD IDOK',
        "  SetErrorLevel 1",
        "  Abort",
        "aivoraInstallDone:",
        "SectionEnd",
        'Section "Uninstall"',
    ]
    for relative in reversed(list(files)):
        escaped = relative.replace("/", "\\").replace("$", "$$").replace('"', '$\\"')
        lines.append('  Delete "$INSTDIR\\' + escaped + '"')
    lines += [
        '  Delete "$INSTDIR\\Uninstall.exe"',
        '  Delete "$SMPROGRAMS\\AIVORA Dev Core\\AIVORA Dev Core.lnk"',
        '  Delete "$SMPROGRAMS\\AIVORA Dev Core\\Uninstall.lnk"',
        '  RMDir "$SMPROGRAMS\\AIVORA Dev Core"',
        '  DeleteRegKey HKCU "${INSTALL_REGISTRY_KEY}"',
    ]
    for directory in sorted(directories, key=lambda value: (value.count("/"), value), reverse=True):
        escaped = directory.replace("/", "\\").replace("$", "$$").replace('"', '$\\"')
        lines.append('  RMDir "$INSTDIR\\' + escaped + '"')
    lines += ['  RMDir "$INSTDIR"', "SectionEnd", ""]
    script = "\n".join(lines)
    if "::" in script or "RMDir /r" in script or "ExecWait" in script:
        raise ValueError("Unexpected plugin/process/recursive-delete instruction")
    return script, files


def build(stage: Path, tools: dict, evidence: Path) -> Path:
    app = stage / "installer-output/win-unpacked"
    installer = stage / "installer-output/AIVORA-Dev-Core-0.1.0-dev.core-win-x64.exe"
    if installer.exists():
        raise ValueError("Refusing to overwrite an existing installer")
    nsis = Path(tools["environment"]["ELECTRON_BUILDER_NSIS_DIR"])
    if digest(nsis / "COPYING") != NSIS_COPYING_SHA256:
        raise ValueError("Pinned NSIS core licence material changed")
    script, files = generate_script(app, installer, stage / "build/installer.nsh")
    script_path = stage / "build/development-core.nsi"
    script_path.write_text(script, encoding="utf-8-sig")
    # Compiler bytes originate from the already SHA-verified official NSIS archive.
    compiler = nsis / "Bin/makensis.exe"
    if digest(compiler) != NSIS_WINDOWS_COMPILER_SHA256:
        raise ValueError("Pinned NSIS compiler bytes changed")
    subprocess.run(
        [str(compiler), "/V2", str(script_path)],
        check=True,
        cwd=stage / "build",
        env={**os.environ, "NSISDIR": str(nsis)},
    )
    if program_files(app) != files:
        raise ValueError("Packaged application files changed during installer compilation")
    receipt = {
        "schema_version": 1,
        "profile": "DEVELOPMENT_CORE",
        "installer_engine": "first-party-nsis-core-zlib",
        "nsis_version": "3.0.4.1",
        "nsis_copying_sha256": NSIS_COPYING_SHA256,
        "compiler_sha256": digest(compiler),
        "script_sha256": digest(script_path),
        "hook_sha256": digest(stage / "build/installer.nsh"),
        "installed_program_files": files,
        "installer_sha256": digest(installer),
        "third_party_resource_plugins": [],
        "uninstall": "explicit-program-file-list-and-empty-directories-only",
        "existing_install_or_data": "ABORT",
        "release_approved": False,
    }
    (evidence / "NSIS-CORE-BUILD.json").write_text(json.dumps(receipt, indent=2) + "\n")
    return installer


def verify(stage: Path, receipt: dict) -> None:
    if (
        receipt.get("schema_version") != 1
        or receipt.get("profile") != "DEVELOPMENT_CORE"
        or receipt.get("installer_engine") != "first-party-nsis-core-zlib"
        or receipt.get("third_party_resource_plugins") != []
        or receipt.get("compiler_sha256") != NSIS_WINDOWS_COMPILER_SHA256
        or receipt.get("release_approved") is not False
    ):
        raise ValueError("Expected the pinned plugin-free Windows installer build receipt")
    app = stage / "installer-output/win-unpacked"
    installer = stage / "installer-output/AIVORA-Dev-Core-0.1.0-dev.core-win-x64.exe"
    hook = stage / "build/installer.nsh"
    script_path = stage / "build/development-core.nsi"
    expected_script, files = generate_script(app, installer, hook)
    if (
        files != receipt["installed_program_files"]
        or script_path.read_text(encoding="utf-8-sig") != expected_script
        or digest(script_path) != receipt["script_sha256"]
        or digest(hook) != receipt["hook_sha256"]
        or digest(hook) != digest(HERE / "installer.dev-core.nsh")
        or digest(installer) != receipt["installer_sha256"]
        or digest(app / "resources/licenses/NSIS-core-COPYING.txt") != NSIS_COPYING_SHA256
    ):
        raise ValueError("Plugin-free installer script, package or licence evidence changed")
    electron_licenses = {
        "LICENSE.electron.txt": "5154e165bd6c2cc0cfbcd8916498c7abab0497923bafcd5cb07673fe8480087d",
        "LICENSES.chromium.html": (
            "b911161e6594ec76b872498b423c54406168f2974e0d407a847f7de1e5ff94dd"
        ),
    }
    for name, expected in electron_licenses.items():
        if digest(app / name) != expected:
            raise ValueError("Electron's supplied licence text was not preserved")
