/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["listProjects"];
        put?: never;
        /** Create Project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/source-manifest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source Manifest */
        get: operations["getSourceManifest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["listSources"];
        put?: never;
        /** Import Text Source */
        post: operations["importTextSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["getSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/story-bible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Bible */
        get: operations["getStoryBibleIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/story-bible/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Story Bible Version */
        post: operations["createStoryBibleVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/story-bible/versions/{version_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Story Bible Version */
        get: operations["getStoryBibleVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArtifactHeadData */
        ArtifactHeadData: {
            /** Accepted Version Id */
            accepted_version_id?: string | null;
            /** Artifact Id */
            artifact_id: string;
            /** Latest Version Id */
            latest_version_id: string;
            /** Review Evidence Revision */
            review_evidence_revision: number;
            /** Review Submission Id */
            review_submission_id: string | null;
            /** Review Version Id */
            review_version_id?: string | null;
            /** Revision */
            revision: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** BooleanStateValueV1 */
        BooleanStateValueV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "boolean";
            /** Value */
            value: boolean;
        };
        /** @enum {string} */
        CanonCertainty: "certain" | "likely" | "ambiguous" | "intentionally_unreliable";
        /** @enum {string} */
        CanonStatus: "proposed" | "confirmed" | "contested" | "rejected";
        /** CharacterEntityV1 */
        CharacterEntityV1: {
            /** Aliases */
            aliases?: string[];
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "character";
            /** Name */
            name: string;
        };
        /** CharacterFactDraftV1 */
        CharacterFactDraftV1: {
            /** Attribute */
            attribute: string;
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Character Id */
            character_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "character_fact";
            origin: components["schemas"]["FactOrigin"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            validity?: components["schemas"]["EventValidityDraftV1"] | null;
            /** Value */
            value: string;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** CharacterFactV1 */
        CharacterFactV1: {
            /** Attribute */
            attribute: string;
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Character Id */
            character_id: string;
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "character_fact";
            origin: components["schemas"]["FactOrigin"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            validity?: components["schemas"]["EventValidityV1"] | null;
            /** Value */
            value: string;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** ClientRefV1 */
        ClientRefV1: {
            /** Client Key */
            client_key: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            ref_type: "client_key";
        };
        /** CostumeEntityV1 */
        CostumeEntityV1: {
            /** Aliases */
            aliases?: string[];
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "costume";
            /** Name */
            name: string;
        };
        /** CostumeFactDraftV1 */
        CostumeFactDraftV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Costume Id */
            costume_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "costume_fact";
            origin: components["schemas"]["FactOrigin"];
            /**
             * Property Key
             * @enum {string}
             */
            property_key: "wearer" | "location" | "condition" | "appearance";
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            validity?: components["schemas"]["EventValidityDraftV1"] | null;
            /** Value */
            value: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueDraftV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** CostumeFactV1 */
        CostumeFactV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Costume Id */
            costume_id: string;
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "costume_fact";
            origin: components["schemas"]["FactOrigin"];
            /**
             * Property Key
             * @enum {string}
             */
            property_key: "wearer" | "location" | "condition" | "appearance";
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            validity?: components["schemas"]["EventValidityV1"] | null;
            /** Value */
            value: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /**
             * Aspect Ratio
             * @default 9:16
             * @constant
             */
            aspect_ratio: "9:16";
            /** Name */
            name: string;
            /**
             * Source Language
             * @default zh-CN
             * @constant
             */
            source_language: "zh-CN";
            /**
             * Target Duration Seconds
             * @default 90
             */
            target_duration_seconds: number;
        };
        /** CreateStoryBibleVersionRequest */
        CreateStoryBibleVersionRequest: {
            /** Change Summary */
            change_summary: string;
            content: components["schemas"]["StoryBibleContentDraftV1"];
            /** Parent Version Id */
            parent_version_id?: string | null;
            /** Source Spans */
            source_spans: components["schemas"]["StorySourceSpanDraftV1"][];
        };
        /** @enum {string} */
        EntityKind: "character" | "location" | "organization" | "prop" | "costume";
        /** EntityStateValueDraftV1 */
        EntityStateValueDraftV1: {
            /** Entity Id */
            entity_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "entity_ref";
        };
        /** EntityStateValueV1 */
        EntityStateValueV1: {
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "entity_ref";
        };
        /**
         * ErrorBody
         * @description Stable machine-readable error details.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * ErrorResponse
         * @description Error envelope shared by all HTTP boundaries.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** EventFactDraftV1 */
        EventFactDraftV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Caused By Fact Ids */
            caused_by_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "event_fact";
            /** Location Id */
            location_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
            origin: components["schemas"]["FactOrigin"];
            /** Participants */
            participants: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Source Narrative Order */
            source_narrative_order: number;
            source_reliability: components["schemas"]["SourceReliability"];
            /** State Changes */
            state_changes?: components["schemas"]["StateChangeDraftV1"][];
            /** Story Time Order */
            story_time_order: number;
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Temporal Relations */
            temporal_relations?: components["schemas"]["TemporalRelationDraftV1"][];
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** EventFactV1 */
        EventFactV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Caused By Fact Ids */
            caused_by_fact_ids?: string[];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "event_fact";
            /** Location Id */
            location_id?: string | null;
            origin: components["schemas"]["FactOrigin"];
            /** Participants */
            participants: string[];
            /** Source Narrative Order */
            source_narrative_order: number;
            source_reliability: components["schemas"]["SourceReliability"];
            /** State Changes */
            state_changes?: components["schemas"]["StateChangeV1"][];
            /** Story Time Order */
            story_time_order: number;
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            /** Temporal Relations */
            temporal_relations?: components["schemas"]["TemporalRelationV1"][];
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** EventValidityDraftV1 */
        EventValidityDraftV1: {
            /** Ends After Event Fact Id */
            ends_after_event_fact_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
            /** Starts After Event Fact Id */
            starts_after_event_fact_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** EventValidityV1 */
        EventValidityV1: {
            /** Ends After Event Fact Id */
            ends_after_event_fact_id?: string | null;
            /** Starts After Event Fact Id */
            starts_after_event_fact_id?: string | null;
        };
        /** FactConflictDraftV1 */
        FactConflictDraftV1: {
            /** Conflict Id */
            conflict_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Conflict Type */
            conflict_type: string;
            /** Fact Ids */
            fact_ids: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Resolution Fact Id */
            resolution_fact_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
            /** Resolution Reason */
            resolution_reason?: string | null;
            /** Responsible Role */
            responsible_role: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "major" | "minor" | "note";
            /**
             * Status
             * @enum {string}
             */
            status: "unresolved" | "resolved_as_source_ambiguity" | "resolved_by_user_decision";
        };
        /** FactConflictV1 */
        FactConflictV1: {
            /** Conflict Id */
            conflict_id: string;
            /** Conflict Type */
            conflict_type: string;
            /** Fact Ids */
            fact_ids: string[];
            /** Resolution Fact Id */
            resolution_fact_id?: string | null;
            /** Resolution Reason */
            resolution_reason?: string | null;
            /** Responsible Role */
            responsible_role: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "major" | "minor" | "note";
            /**
             * Status
             * @enum {string}
             */
            status: "unresolved" | "resolved_as_source_ambiguity" | "resolved_by_user_decision";
        };
        /** @enum {string} */
        FactImportance: "core" | "supporting" | "detail";
        /** @enum {string} */
        FactOrigin: "source_explicit_assertion" | "source_interpretation" | "user_decision" | "ai_inference";
        /**
         * HealthData
         * @description Stable service identity returned by the health endpoint.
         */
        HealthData: {
            /**
             * Service
             * @default aijian-api
             * @constant
             */
            service: "aijian-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * HealthResponse
         * @description Versioned health response envelope.
         */
        HealthResponse: {
            data: components["schemas"]["HealthData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ImportTextSourceRequest */
        ImportTextSourceRequest: {
            /** Content Base64 */
            content_base64: string;
            /** Filename */
            filename: string;
            /**
             * Media Type
             * @default text/plain
             * @constant
             */
            media_type: "text/plain";
        };
        /** LocationEntityV1 */
        LocationEntityV1: {
            /** Aliases */
            aliases?: string[];
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "location";
            /** Name */
            name: string;
        };
        /** LocationFactDraftV1 */
        LocationFactDraftV1: {
            /** Attribute */
            attribute: string;
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "location_fact";
            /** Location Id */
            location_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            origin: components["schemas"]["FactOrigin"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            validity?: components["schemas"]["EventValidityDraftV1"] | null;
            /** Value */
            value: string;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** LocationFactV1 */
        LocationFactV1: {
            /** Attribute */
            attribute: string;
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "location_fact";
            /** Location Id */
            location_id: string;
            origin: components["schemas"]["FactOrigin"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            validity?: components["schemas"]["EventValidityV1"] | null;
            /** Value */
            value: string;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** NumberStateValueV1 */
        NumberStateValueV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "number";
            /** Value */
            value: number;
        };
        /** OrganizationEntityV1 */
        OrganizationEntityV1: {
            /** Aliases */
            aliases?: string[];
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "organization";
            /** Name */
            name: string;
        };
        /** OrganizationFactDraftV1 */
        OrganizationFactDraftV1: {
            /** Attribute */
            attribute: string;
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "organization_fact";
            /** Organization Id */
            organization_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            origin: components["schemas"]["FactOrigin"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            validity?: components["schemas"]["EventValidityDraftV1"] | null;
            /** Value */
            value: string;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** OrganizationFactV1 */
        OrganizationFactV1: {
            /** Attribute */
            attribute: string;
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "organization_fact";
            /** Organization Id */
            organization_id: string;
            origin: components["schemas"]["FactOrigin"];
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            validity?: components["schemas"]["EventValidityV1"] | null;
            /** Value */
            value: string;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** PermanentRefV1 */
        PermanentRefV1: {
            /** Permanent Id */
            permanent_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            ref_type: "permanent_id";
        };
        /** ProjectData */
        ProjectData: {
            /**
             * Aspect Ratio
             * @constant
             */
            aspect_ratio: "9:16";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            /**
             * Source Language
             * @constant
             */
            source_language: "zh-CN";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /** Target Duration Seconds */
            target_duration_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Data */
            data: components["schemas"]["ProjectData"][];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ProjectResponse */
        ProjectResponse: {
            data: components["schemas"]["ProjectData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** PropEntityV1 */
        PropEntityV1: {
            /** Aliases */
            aliases?: string[];
            /** Entity Id */
            entity_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "prop";
            /** Name */
            name: string;
        };
        /** PropFactDraftV1 */
        PropFactDraftV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "prop_fact";
            origin: components["schemas"]["FactOrigin"];
            /** Prop Id */
            prop_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /**
             * Property Key
             * @enum {string}
             */
            property_key: "holder" | "location" | "condition" | "appearance";
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            validity?: components["schemas"]["EventValidityDraftV1"] | null;
            /** Value */
            value: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueDraftV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** PropFactV1 */
        PropFactV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "prop_fact";
            origin: components["schemas"]["FactOrigin"];
            /** Prop Id */
            prop_id: string;
            /**
             * Property Key
             * @enum {string}
             */
            property_key: "holder" | "location" | "condition" | "appearance";
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            validity?: components["schemas"]["EventValidityV1"] | null;
            /** Value */
            value: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** RelationshipFactDraftV1 */
        RelationshipFactDraftV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "relationship_fact";
            /** Object Entity Id */
            object_entity_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            origin: components["schemas"]["FactOrigin"];
            /** Predicate */
            predicate: string;
            source_reliability: components["schemas"]["SourceReliability"];
            /** Subject Entity Id */
            subject_entity_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            validity?: components["schemas"]["EventValidityDraftV1"] | null;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** RelationshipFactV1 */
        RelationshipFactV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "relationship_fact";
            /** Object Entity Id */
            object_entity_id: string;
            origin: components["schemas"]["FactOrigin"];
            /** Predicate */
            predicate: string;
            source_reliability: components["schemas"]["SourceReliability"];
            /** Subject Entity Id */
            subject_entity_id: string;
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            validity?: components["schemas"]["EventValidityV1"] | null;
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
        /** SourceBlockData */
        SourceBlockData: {
            /** Chapter Index */
            chapter_index: number;
            /** Content Sha256 */
            content_sha256: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "chapter_heading" | "paragraph";
            /** Normalized End Byte */
            normalized_end_byte: number;
            /** Normalized Start Byte */
            normalized_start_byte: number;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
        };
        /** SourceDocumentData */
        SourceDocumentData: {
            /** Block Count */
            block_count: number;
            /** Blocks */
            blocks: components["schemas"]["SourceBlockData"][];
            /** Byte Size */
            byte_size: number;
            /** Chapter Count */
            chapter_count: number;
            /**
             * Encoding
             * @constant
             */
            encoding: "utf-8";
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Media Type
             * @constant
             */
            media_type: "text/plain";
            /** Project Id */
            project_id: string;
            /** Raw Sha256 */
            raw_sha256: string;
        };
        /** SourceDocumentListResponse */
        SourceDocumentListResponse: {
            /** Data */
            data: components["schemas"]["SourceDocumentSummaryData"][];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** SourceDocumentResponse */
        SourceDocumentResponse: {
            data: components["schemas"]["SourceDocumentData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** SourceDocumentSummaryData */
        SourceDocumentSummaryData: {
            /** Block Count */
            block_count: number;
            /** Byte Size */
            byte_size: number;
            /** Chapter Count */
            chapter_count: number;
            /**
             * Encoding
             * @constant
             */
            encoding: "utf-8";
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Media Type
             * @constant
             */
            media_type: "text/plain";
            /** Project Id */
            project_id: string;
            /** Raw Sha256 */
            raw_sha256: string;
        };
        /** SourceManifestBlockV1 */
        SourceManifestBlockV1: {
            /** Chapter Index */
            chapter_index: number;
            /** Content Sha256 */
            content_sha256: string;
            /** End Byte */
            end_byte: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "chapter_heading" | "paragraph";
            /** Ordinal */
            ordinal: number;
            /** Source Block Id */
            source_block_id: string;
            /** Start Byte */
            start_byte: number;
        };
        /** SourceManifestContentV1 */
        SourceManifestContentV1: {
            /** Documents */
            documents: components["schemas"]["SourceManifestDocumentV1"][];
            /** Exclusions */
            exclusions?: string[];
            /**
             * Scope Type
             * @default full_work
             * @constant
             */
            scope_type: "full_work";
        };
        /** SourceManifestData */
        SourceManifestData: {
            accepted_version: components["schemas"]["SourceManifestVersionData"] | null;
            head: components["schemas"]["ArtifactHeadData"];
            latest_version: components["schemas"]["SourceManifestVersionData"];
            /** Project Id */
            project_id: string;
            review_version: components["schemas"]["SourceManifestVersionData"] | null;
        };
        /** SourceManifestDocumentV1 */
        SourceManifestDocumentV1: {
            /** Blocks */
            blocks: components["schemas"]["SourceManifestBlockV1"][];
            /** Byte Size */
            byte_size: number;
            /** Chapter Count */
            chapter_count: number;
            /**
             * Encoding
             * @constant
             */
            encoding: "utf-8";
            /** Filename */
            filename: string;
            /** Import Order */
            import_order: number;
            /**
             * Media Type
             * @constant
             */
            media_type: "text/plain";
            /** Normalized Sha256 */
            normalized_sha256: string;
            /** Raw Sha256 */
            raw_sha256: string;
            /** Source Document Id */
            source_document_id: string;
        };
        /** SourceManifestResponse */
        SourceManifestResponse: {
            data: components["schemas"]["SourceManifestData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** SourceManifestVersionData */
        SourceManifestVersionData: {
            /** Artifact Id */
            artifact_id: string;
            /** Change Summary */
            change_summary: string;
            content: components["schemas"]["SourceManifestContentV1"];
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0.0";
            /** Version Number */
            version_number: number;
        };
        /** @enum {string} */
        SourceReliability: "reliable" | "uncertain" | "unreliable" | "not_applicable";
        /** SourceScopeDocumentV1 */
        SourceScopeDocumentV1: {
            /** Chapter Indices */
            chapter_indices: number[];
            /** Raw Sha256 */
            raw_sha256: string;
            /** Source Block Ids */
            source_block_ids: string[];
            /** Source Document Id */
            source_document_id: string;
        };
        /** StateChangeDraftV1 */
        StateChangeDraftV1: {
            /** After */
            after?: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueDraftV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Before */
            before?: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueDraftV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Entity Id */
            entity_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            property_key: components["schemas"]["StatePropertyKey"];
        };
        /** StateChangeV1 */
        StateChangeV1: {
            /** After */
            after?: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Before */
            before?: (components["schemas"]["TextStateValueV1"] | components["schemas"]["EntityStateValueV1"] | components["schemas"]["BooleanStateValueV1"] | components["schemas"]["NumberStateValueV1"]) | null;
            /** Entity Id */
            entity_id: string;
            property_key: components["schemas"]["StatePropertyKey"];
        };
        /** @enum {string} */
        StatePropertyKey: "holder" | "wearer" | "location" | "condition" | "possession" | "relationship_status" | "alive" | "appearance";
        /** StoryBibleContentDraftV1 */
        StoryBibleContentDraftV1: {
            /** Conflicts */
            conflicts?: components["schemas"]["FactConflictDraftV1"][];
            /** Entities */
            entities: components["schemas"]["StoryEntityDraftV1"][];
            /** Facts */
            facts: (components["schemas"]["CharacterFactDraftV1"] | components["schemas"]["LocationFactDraftV1"] | components["schemas"]["RelationshipFactDraftV1"] | components["schemas"]["EventFactDraftV1"] | components["schemas"]["WorldRuleFactDraftV1"] | components["schemas"]["OrganizationFactDraftV1"] | components["schemas"]["PropFactDraftV1"] | components["schemas"]["CostumeFactDraftV1"])[];
            /** Logline */
            logline: string;
            /** Questions */
            questions?: components["schemas"]["StoryQuestionDraftV1"][];
            source_scope: components["schemas"]["StorySourceScopeV1"];
            /** Title */
            title: string;
        };
        /** StoryBibleContentV1 */
        StoryBibleContentV1: {
            /** Conflicts */
            conflicts?: components["schemas"]["FactConflictV1"][];
            /** Entities */
            entities: (components["schemas"]["CharacterEntityV1"] | components["schemas"]["LocationEntityV1"] | components["schemas"]["OrganizationEntityV1"] | components["schemas"]["PropEntityV1"] | components["schemas"]["CostumeEntityV1"])[];
            /** Facts */
            facts: (components["schemas"]["CharacterFactV1"] | components["schemas"]["LocationFactV1"] | components["schemas"]["RelationshipFactV1"] | components["schemas"]["EventFactV1"] | components["schemas"]["WorldRuleFactV1"] | components["schemas"]["OrganizationFactV1"] | components["schemas"]["PropFactV1"] | components["schemas"]["CostumeFactV1"])[];
            /** Logline */
            logline: string;
            /** Questions */
            questions?: components["schemas"]["StoryQuestionV1"][];
            source_scope: components["schemas"]["StorySourceScopeV1"];
            /** Title */
            title: string;
        };
        /** StoryBibleIndexData */
        StoryBibleIndexData: {
            accepted_version: components["schemas"]["StoryBibleVersionSummaryData"] | null;
            head: components["schemas"]["ArtifactHeadData"];
            latest_version: components["schemas"]["StoryBibleVersionSummaryData"];
            /** Project Id */
            project_id: string;
            review_version: components["schemas"]["StoryBibleVersionSummaryData"] | null;
        };
        /** StoryBibleIndexResponse */
        StoryBibleIndexResponse: {
            data: components["schemas"]["StoryBibleIndexData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** StoryBibleVersionCreatedData */
        StoryBibleVersionCreatedData: {
            head: components["schemas"]["ArtifactHeadData"];
            /** Id Map */
            id_map: {
                [key: string]: string;
            };
            version: components["schemas"]["StoryBibleVersionData"];
        };
        /** StoryBibleVersionCreatedResponse */
        StoryBibleVersionCreatedResponse: {
            data: components["schemas"]["StoryBibleVersionCreatedData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** StoryBibleVersionData */
        StoryBibleVersionData: {
            /** Artifact Id */
            artifact_id: string;
            /** Change Summary */
            change_summary: string;
            content: components["schemas"]["StoryBibleContentV1"];
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0.0";
            /** Source Spans */
            source_spans: components["schemas"]["StorySourceSpanData"][];
            /** Version Number */
            version_number: number;
        };
        /** StoryBibleVersionReadData */
        StoryBibleVersionReadData: {
            head: components["schemas"]["ArtifactHeadData"];
            /** Project Id */
            project_id: string;
            version: components["schemas"]["StoryBibleVersionData"];
        };
        /** StoryBibleVersionResponse */
        StoryBibleVersionResponse: {
            data: components["schemas"]["StoryBibleVersionReadData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** StoryBibleVersionSummaryData */
        StoryBibleVersionSummaryData: {
            /** Artifact Id */
            artifact_id: string;
            /** Change Summary */
            change_summary: string;
            /** Content Hash */
            content_hash: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Parent Version Id */
            parent_version_id?: string | null;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1.0.0";
            /** Version Number */
            version_number: number;
        };
        /** StoryEntityDraftV1 */
        StoryEntityDraftV1: {
            /** Aliases */
            aliases?: string[];
            /** Entity Id */
            entity_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            kind: components["schemas"]["EntityKind"];
            /** Name */
            name: string;
        };
        /** StoryQuestionDraftV1 */
        StoryQuestionDraftV1: {
            /** Blocking */
            blocking: boolean;
            /** Question */
            question: string;
            /** Question Id */
            question_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Resolution */
            resolution?: string | null;
            /** Responsible Role */
            responsible_role: string;
            /** Scope Id */
            scope_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "artifact" | "entity" | "fact" | "source_document";
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "major" | "minor" | "note";
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved";
        };
        /** StoryQuestionV1 */
        StoryQuestionV1: {
            /** Blocking */
            blocking: boolean;
            /** Question */
            question: string;
            /** Question Id */
            question_id: string;
            /** Resolution */
            resolution?: string | null;
            /** Responsible Role */
            responsible_role: string;
            /** Scope Id */
            scope_id?: string | null;
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "artifact" | "entity" | "fact" | "source_document";
            /**
             * Severity
             * @enum {string}
             */
            severity: "blocking" | "major" | "minor" | "note";
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "resolved";
        };
        /** StorySourceScopeV1 */
        StorySourceScopeV1: {
            /** Documents */
            documents: components["schemas"]["SourceScopeDocumentV1"][];
            /** Exclusions */
            exclusions?: string[];
            /**
             * Scope Type
             * @enum {string}
             */
            scope_type: "full_work" | "selected_range";
            /** Source Manifest Version Id */
            source_manifest_version_id: string;
        };
        /** StorySourceSpanData */
        StorySourceSpanData: {
            /** Claim */
            claim: string;
            /** End Byte */
            end_byte: number;
            /** Fact Id */
            fact_id: string;
            /** Id */
            id: string;
            /** Quote Hash */
            quote_hash: string;
            /**
             * Role
             * @enum {string}
             */
            role: "supports" | "contradicts" | "context";
            /** Source Block Id */
            source_block_id: string;
            /** Source Document Id */
            source_document_id: string;
            /** Start Byte */
            start_byte: number;
        };
        /** StorySourceSpanDraftV1 */
        StorySourceSpanDraftV1: {
            /** Claim */
            claim: string;
            /** End Byte */
            end_byte: number;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /**
             * Role
             * @enum {string}
             */
            role: "supports" | "contradicts" | "context";
            /** Source Block Id */
            source_block_id: string;
            /** Source Document Id */
            source_document_id: string;
            /** Start Byte */
            start_byte: number;
        };
        /** TemporalRelationDraftV1 */
        TemporalRelationDraftV1: {
            /** Other Event Fact Id */
            other_event_fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /**
             * Relation
             * @enum {string}
             */
            relation: "before" | "after" | "simultaneous";
        };
        /** TemporalRelationV1 */
        TemporalRelationV1: {
            /** Other Event Fact Id */
            other_event_fact_id: string;
            /**
             * Relation
             * @enum {string}
             */
            relation: "before" | "after" | "simultaneous";
        };
        /** TextStateValueV1 */
        TextStateValueV1: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "text";
            /** Value */
            value: string;
        };
        /** WorldRuleFactDraftV1 */
        WorldRuleFactDraftV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Exceptions */
            exceptions?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"];
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "world_rule_fact";
            origin: components["schemas"]["FactOrigin"];
            /** Rule */
            rule: string;
            /** Rule Scope */
            rule_scope: string;
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"])[];
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: (components["schemas"]["PermanentRefV1"] | components["schemas"]["ClientRefV1"]) | null;
        };
        /** WorldRuleFactV1 */
        WorldRuleFactV1: {
            canon_certainty: components["schemas"]["CanonCertainty"];
            canon_status: components["schemas"]["CanonStatus"];
            /** Decision Reason */
            decision_reason?: string | null;
            /** Derived From Fact Ids */
            derived_from_fact_ids?: string[];
            /** Exceptions */
            exceptions?: string[];
            /** Extraction Confidence Bps */
            extraction_confidence_bps?: number | null;
            /** Fact Id */
            fact_id: string;
            /** Impact Scope */
            impact_scope?: string[];
            importance: components["schemas"]["FactImportance"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "world_rule_fact";
            origin: components["schemas"]["FactOrigin"];
            /** Rule */
            rule: string;
            /** Rule Scope */
            rule_scope: string;
            source_reliability: components["schemas"]["SourceReliability"];
            /** Supersedes Fact Ids */
            supersedes_fact_ids?: string[];
            /** Viewpoint Entity Id */
            viewpoint_entity_id?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSourceManifest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceManifestResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or SourceManifest not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentListResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    importTextSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTextSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Invalid source file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source already imported */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source file too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStoryBibleIndex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryBibleIndexResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or StoryBible not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createStoryBibleVersion: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStoryBibleVersionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryBibleVersionCreatedResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or parent artifact not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Accepted source dependency is unavailable */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artifact revision changed */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description StoryBible response too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description If-Match is required for a revision */
            428: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStoryBibleVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryBibleVersionResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or StoryBible version not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description StoryBible response too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
