/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["listProjects"];
        put?: never;
        /** Create Project */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["listSources"];
        put?: never;
        /** Import Text Source */
        post: operations["importTextSource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["getSource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /**
             * Aspect Ratio
             * @default 9:16
             * @constant
             */
            aspect_ratio: "9:16";
            /** Name */
            name: string;
            /**
             * Source Language
             * @default zh-CN
             * @constant
             */
            source_language: "zh-CN";
            /**
             * Target Duration Seconds
             * @default 90
             */
            target_duration_seconds: number;
        };
        /**
         * ErrorBody
         * @description Stable machine-readable error details.
         */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details: {
                [key: string]: string;
            };
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /**
         * ErrorResponse
         * @description Error envelope shared by all HTTP boundaries.
         */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /**
         * HealthData
         * @description Stable service identity returned by the health endpoint.
         */
        HealthData: {
            /**
             * Service
             * @default aijian-api
             * @constant
             */
            service: "aijian-api";
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
        };
        /**
         * HealthResponse
         * @description Versioned health response envelope.
         */
        HealthResponse: {
            data: components["schemas"]["HealthData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ImportTextSourceRequest */
        ImportTextSourceRequest: {
            /** Content Base64 */
            content_base64: string;
            /** Filename */
            filename: string;
            /**
             * Media Type
             * @default text/plain
             * @constant
             */
            media_type: "text/plain";
        };
        /** ProjectData */
        ProjectData: {
            /**
             * Aspect Ratio
             * @constant
             */
            aspect_ratio: "9:16";
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Revision */
            revision: number;
            /**
             * Source Language
             * @constant
             */
            source_language: "zh-CN";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "archived";
            /** Target Duration Seconds */
            target_duration_seconds: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProjectListResponse */
        ProjectListResponse: {
            /** Data */
            data: components["schemas"]["ProjectData"][];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ProjectResponse */
        ProjectResponse: {
            data: components["schemas"]["ProjectData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** SourceBlockData */
        SourceBlockData: {
            /** Chapter Index */
            chapter_index: number;
            /** Content Sha256 */
            content_sha256: string;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "chapter_heading" | "paragraph";
            /** Normalized End Byte */
            normalized_end_byte: number;
            /** Normalized Start Byte */
            normalized_start_byte: number;
            /** Ordinal */
            ordinal: number;
            /** Text */
            text: string;
        };
        /** SourceDocumentData */
        SourceDocumentData: {
            /** Block Count */
            block_count: number;
            /** Blocks */
            blocks: components["schemas"]["SourceBlockData"][];
            /** Byte Size */
            byte_size: number;
            /** Chapter Count */
            chapter_count: number;
            /**
             * Encoding
             * @constant
             */
            encoding: "utf-8";
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Media Type
             * @constant
             */
            media_type: "text/plain";
            /** Project Id */
            project_id: string;
            /** Raw Sha256 */
            raw_sha256: string;
        };
        /** SourceDocumentListResponse */
        SourceDocumentListResponse: {
            /** Data */
            data: components["schemas"]["SourceDocumentSummaryData"][];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** SourceDocumentResponse */
        SourceDocumentResponse: {
            data: components["schemas"]["SourceDocumentData"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** SourceDocumentSummaryData */
        SourceDocumentSummaryData: {
            /** Block Count */
            block_count: number;
            /** Byte Size */
            byte_size: number;
            /** Chapter Count */
            chapter_count: number;
            /**
             * Encoding
             * @constant
             */
            encoding: "utf-8";
            /** Filename */
            filename: string;
            /** Id */
            id: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /**
             * Media Type
             * @constant
             */
            media_type: "text/plain";
            /** Project Id */
            project_id: string;
            /** Raw Sha256 */
            raw_sha256: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentListResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    importTextSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportTextSourceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Invalid source file */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source already imported */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Source file too large */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceDocumentResponse"];
                };
            };
            /** @description Sidecar authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sidecar request boundary rejected */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project or source not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
