/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** ArtifactHeadData */
    ArtifactHeadData: {
      /**
       * Accepted Version Id
       * @default null
       */
      accepted_version_id: string | null;
      /** Artifact Id */
      artifact_id: string;
      /** Latest Version Id */
      latest_version_id: string;
      /** Review Evidence Revision */
      review_evidence_revision: number;
      /** Review Submission Id */
      review_submission_id: string | null;
      /**
       * Review Version Id
       * @default null
       */
      review_version_id: string | null;
      /** Revision */
      revision: number;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** ConfirmationChallengeData */
    ConfirmationChallengeData: {
      /**
       * Action
       * @enum {string}
       */
      action: "submit" | "signoff" | "decision";
      /** Artifact Id */
      artifact_id: string;
      /** Consumed At */
      consumed_at: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Gate
       * @enum {string}
       */
      gate: "G1" | "G2";
      /** Head Revision */
      head_revision: number;
      /** Id */
      id: string;
      /** Readiness Report Id */
      readiness_report_id: string;
      /** Review Evidence Revision */
      review_evidence_revision: number;
      /** Version Id */
      version_id: string;
    };
    /** ConfirmationRequest */
    ConfirmationRequest: {
      /** Challenge Id */
      challenge_id: string;
      /** Confirmation Token */
      confirmation_token: string;
    };
    /** EmptyActionRequest */
    EmptyActionRequest: Record<string, never>;
    /** GateDecisionData */
    GateDecisionData: {
      /** Actor Id */
      actor_id: string;
      /** Actor Role */
      actor_role: string;
      /** Artifact Id */
      artifact_id: string;
      /**
       * Decided At
       * Format: date-time
       */
      decided_at: string;
      /**
       * Decision
       * @enum {string}
       */
      decision: "approved" | "approved_with_waiver" | "rejected";
      /**
       * Gate
       * @enum {string}
       */
      gate: "G1" | "G2";
      /** Id */
      id: string;
      /** Rationale */
      rationale: string;
      /** Readiness Report Id */
      readiness_report_id: string;
      /** Self Review */
      self_review: boolean;
      /** Submission Id */
      submission_id: string;
      /** Version Id */
      version_id: string;
    };
    /** GateDecisionRequest */
    GateDecisionRequest: {
      /** Challenge Id */
      challenge_id: string;
      /** Confirmation Token */
      confirmation_token: string;
      /**
       * Decision
       * @constant
       */
      decision: "approved";
      /** Rationale */
      rationale: string;
    };
    /** GateDecisionResponse */
    GateDecisionResponse: {
      data: components["schemas"]["GateDecisionResultData"];
      /**
       * Request Id
       * Format: uuid
       */
      request_id: string;
    };
    /** GateDecisionResultData */
    GateDecisionResultData: {
      decision: components["schemas"]["GateDecisionData"];
      head: components["schemas"]["ArtifactHeadData"];
    };
    /** GateReadinessReportData */
    GateReadinessReportData: {
      /** Artifact Id */
      artifact_id: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /**
       * Gate
       * @enum {string}
       */
      gate: "G1" | "G2";
      /** Head Revision */
      head_revision: number;
      /** Id */
      id: string;
      /** Policy Code */
      policy_code: string;
      /** Policy Version */
      policy_version: string;
      /** Report */
      report: {
        [key: string]: unknown;
      };
      /** Report Hash */
      report_hash: string;
      /** Review Evidence Revision */
      review_evidence_revision: number;
      /**
       * Submission Id
       * @default null
       */
      submission_id: string | null;
      /** Version Id */
      version_id: string;
    };
    /** PrepareGateDecisionRequest */
    PrepareGateDecisionRequest: {
      /**
       * Decision
       * @constant
       */
      decision: "approved";
      /** Rationale */
      rationale: string;
      /** Readiness Report Id */
      readiness_report_id: string;
    };
    /** PreparedReviewActionData */
    PreparedReviewActionData: {
      challenge: components["schemas"]["ConfirmationChallengeData"];
      /** Confirmation Token */
      confirmation_token: string;
      report: components["schemas"]["GateReadinessReportData"];
    };
    /** PreparedReviewActionResponse */
    PreparedReviewActionResponse: {
      data: components["schemas"]["PreparedReviewActionData"];
      /**
       * Request Id
       * Format: uuid
       */
      request_id: string;
    };
    /** ReviewSignoffResponse */
    ReviewSignoffResponse: {
      data: components["schemas"]["ReviewSignoffResultData"];
      /**
       * Request Id
       * Format: uuid
       */
      request_id: string;
    };
    /** ReviewSignoffResultData */
    ReviewSignoffResultData: {
      head: components["schemas"]["ArtifactHeadData"];
      /** Signoffs */
      signoffs: components["schemas"]["RoleSignoffData"][];
    };
    /** ReviewSubmissionData */
    ReviewSubmissionData: {
      /** Artifact Id */
      artifact_id: string;
      /**
       * Gate
       * @enum {string}
       */
      gate: "G1" | "G2";
      /** Id */
      id: string;
      /** Readiness Report Id */
      readiness_report_id: string;
      /**
       * Submitted At
       * Format: date-time
       */
      submitted_at: string;
      /** Submitted By Actor Id */
      submitted_by_actor_id: string;
      /**
       * Supersedes Submission Id
       * @default null
       */
      supersedes_submission_id: string | null;
      /** Version Id */
      version_id: string;
    };
    /** ReviewSubmissionResponse */
    ReviewSubmissionResponse: {
      data: components["schemas"]["ReviewSubmissionResultData"];
      /**
       * Request Id
       * Format: uuid
       */
      request_id: string;
    };
    /** ReviewSubmissionResultData */
    ReviewSubmissionResultData: {
      head: components["schemas"]["ArtifactHeadData"];
      submission: components["schemas"]["ReviewSubmissionData"];
    };
    /** RoleSignoffData */
    RoleSignoffData: {
      /** Actor Id */
      actor_id: string;
      /** Artifact Id */
      artifact_id: string;
      /**
       * Gate
       * @enum {string}
       */
      gate: "G1" | "G2";
      /** Id */
      id: string;
      /** Readiness Report Id */
      readiness_report_id: string;
      /** Review Evidence Revision */
      review_evidence_revision: number;
      /** Role */
      role: string;
      /** Self Review */
      self_review: boolean;
      /**
       * Signed At
       * Format: date-time
       */
      signed_at: string;
      /** Submission Id */
      submission_id: string;
      /**
       * Supersedes Signoff Id
       * @default null
       */
      supersedes_signoff_id: string | null;
      /** Version Id */
      version_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
